### ISSUE TITLE
Request for Dataset Statistics: CIFAR100 and Tiny-ImageNet

### ISSUE THREAD

**Issue by bujuef** [jinhaoduan/SecMI#1]
Dear Authors,

Thanks for your excellent work. I've noted the statistics for CIFAR10 in ./stats/cifar10.train.npz. Would it be feasible for you also to release the statistics for CIFAR100 and Tiny-ImageNet?

Thank you for your time and consideration.

**Comment by jinhaoduan** [comment]
Thanks for your interest.

We didn't calculate the statistics for CIFAR100 or TinyImageNet. The CIFAR10 statistics are originally from [pytorch-ddpm](https://github.com/w86763777/pytorch-ddpm). Please refer to https://github.com/w86763777/pytorch-ddpm/blob/master/score/fid.py for calculating statistics.
