### ISSUE TITLE
Evaluation of conditional diffusion models

### ISSUE THREAD

**Issue by zhaisf** [jinhaoduan/SecMI#3]
Thank you for your amazing work! 

I'd like to inquire if there are evaluation codes about conditional diffusion model in this repository (Sec. 5.5 and Sec. 5.6 in paper) ?

**Comment by jinhaoduan** [comment]
Thank you for your interest. We will update it later.

**Comment by njuaplusplus** [comment]
I am also interested in the implementation for LDM and SD.

**Comment by jinhaoduan** [comment]
We have released SecMI over LDM in https://github.com/jinhaoduan/SecMI-LDM.
