### ISSUE TITLE
Dataset ( train/test split) of your pretrained cifar-10 model

### ISSUE THREAD

**Issue by zhaisf** [jinhaoduan/SecMI#9]
Thank you for your work and for releasing the model weights

However, I obtained different results using your method on the official CIFAR-10 diffusion model [ddpm-cifar10-google](https://huggingface.co/google/ddpm-cifar10-32) with the [cifar10 official train/test split](https://huggingface.co/datasets/cifar10). 

Could you please release the training/testing dataset corresponding to your [pretrained ddpm model](https://drexel0-my.sharepoint.com/:f:/g/personal/jd3734_drexel_edu/EnVid-empkpNvzC_mOfHwv0BpgkDsB_C4RmHO4rIH8BSzw?e=c17NjE)?

**Comment by jinhaoduan** [comment]
1. We have already released the splits https://github.com/jinhaoduan/SecMI/tree/main/mia_evals/member_splits 

3. We didn’t use the official train/test splits. As we mentioned in our paper (Section 5.1), we randomly select 50% of the official training split as the member set and use the rest half as the nonmember set.

**Comment by zhaisf** [comment]
Oh, I see. Thanks!
